# -*- yaml -*-
# METABUILD GENERATED metaconf/metaconf.groovy + metaconf/project/build.yaml.tmpl -> atlasdb/atlasdb-dbkvs-hikari/build.yaml
meta:
  name: AtlasdbDbkvsHikari
  gradle_name: atlasdb-dbkvs-hikari
  use_legacy_revision: true
  source_target_version: 1.6
  skip_dist: true
jars:
  -
    name: atlasdb-dbkvs-hikari
    src:
      - src/main/java
